game_mo82: Player Class Reference
Player Class Reference
Public Member Functions
Player (double X, double Y, double points, Group Root)
Shot makeShot ()
void makeHard ()
void moveSprite (double width, ArrayList< KeyCode > keys)
Public Member Functions inherited from Character
Character (double X, double Y, double points, String fileName, Group myRoot)
boolean checkCollide (Sprite projectile)
void collisionUpdate (Sprite projectile, ArrayList< Sprite > shotsToRemove)
void updateAll (ArrayList< Sprite > shots, ArrayList< Sprite > shotsToRemove)
void setBarLocation (double X, double Y)
void setHP (double points)
double getHP ()
Public Member Functions inherited from Sprite
Sprite (double X, double Y, String fileName, Group myRoot)
void moveSprite ()
void setVelocity (double X, double Y)
Point2D getVelocity ()
Private Attributes
Group myRoot
boolean inHard =false
Additional Inherited Members
Protected Attributes inherited from Character
ProgressBar HPBar
Detailed Description
Definition at line 8 of file Player.java.
Constructor & Destructor Documentation
Player.Player (double X, double Y, double points, Group Root)
Definition at line 11 of file Player.java.
References Character.HPBar, and Character.setBarLocation().
Member Function Documentation
void Player.makeHard ()
Definition at line 26 of file Player.java.
Shot Player.makeShot ()
Definition at line 18 of file Player.java.
References Sprite.getVelocity(), and Sprite.setVelocity().
Referenced by Level1.handleMouseInput().
void Player.moveSprite (double width, ArrayList< KeyCode > keys)
Definition at line 30 of file Player.java.
References Sprite.moveSprite(), and Sprite.setVelocity().
Referenced by Level1.updateSprites().
Member Data Documentation
boolean Player.inHard =false private
Definition at line 10 of file Player.java.
Group Player.myRoot private
Definition at line 9 of file Player.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Player.java