game_mo82: Screen Class Reference
Screen Class Reference
Public Member Functions
void showScreen (Stage s, int width, int height)
Scene init (Stage s, int width, int height)
void startAnim (KeyFrame frame)
void showAndAnim (Stage s, int width, int height, KeyFrame frame)
Protected Attributes
Group myRoot
Detailed Description
Definition at line 9 of file Screen.java.
Member Function Documentation
Scene Screen.init (Stage s, int width, int height)
Definition at line 17 of file Screen.java.
Referenced by showScreen().
void Screen.showAndAnim (Stage s, int width, int height, KeyFrame frame)
Definition at line 28 of file Screen.java.
References showScreen(), and startAnim().
Referenced by Menu.createGame(), and Level1.goNextLevel().
void Screen.showScreen (Stage s, int width, int height)
Definition at line 11 of file Screen.java.
References init().
Referenced by Level1.goGameOver(), Level2.goNextLevel(), showAndAnim(), and Main.start().
void Screen.startAnim (KeyFrame frame)
Definition at line 21 of file Screen.java.
Referenced by showAndAnim().
Member Data Documentation
Group Screen.myRoot protected
Definition at line 10 of file Screen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Screen.java