game_mo82: Level1 Class Reference
Level1 Class Reference
Public Member Functions
Scene init (Stage s, int width, int height)
KeyFrame start (int frameRate)
Enemy getEnemy ()
Player getPlayer ()
Public Member Functions inherited from Screen
void showScreen (Stage s, int width, int height)
Scene init (Stage s, int width, int height)
void startAnim (KeyFrame frame)
void showAndAnim (Stage s, int width, int height, KeyFrame frame)
Private Member Functions
Scene makeScene (int width, int height)
void updateFrame ()
void updateTimer ()
void makeTimer ()
void updateSprites ()
void goNextLevel ()
void goGameOver ()
void clearElements ()
ArrayList< Sprite > returnCollisions (Character character, ArrayList< Sprite > projectiles)
void removeFromScreen (ArrayList< Sprite > projectiles, ArrayList< Sprite > toRemoveArray)
void handleKeyInput (KeyEvent e)
void handleKeyRelease (KeyEvent e)
void handleMouseInput (MouseEvent e)
Private Attributes
double screenWidth
Scene myScene
Group myRoot
Player myPlayer
Enemy myEnemy
Random myGenerator = new Random()
ArrayList< KeyCode > keysPressed
ArrayList< Sprite > Shots
ArrayList< Sprite > Poops
Label timerLabel
int frameCounter =0
IntegerProperty timeSeconds
Stage stage
Static Private Attributes
static final int PLAYER_HP = 50
static final int ENEMY_HP = 100
static final int START_TIME = 60
Additional Inherited Members
Protected Attributes inherited from Screen
Group myRoot
Detailed Description
This represents the primary class for a game/animation.
Author
Robert C. Duvall
Definition at line 32 of file Level1.java.
Member Function Documentation
void Level1.clearElements () private
Definition at line 158 of file Level1.java.
Referenced by goGameOver(), and goNextLevel().
Enemy Level1.getEnemy ()
Needed for subclasses to see enemy
Definition at line 205 of file Level1.java.
References myEnemy.
Player Level1.getPlayer ()
Needed for subclasses to see player
Definition at line 212 of file Level1.java.
References myPlayer.
void Level1.goGameOver () private
Definition at line 149 of file Level1.java.
References clearElements(), Character.getHP(), and Screen.showScreen().
Referenced by updateSprites().
void Level1.goNextLevel () private
Definition at line 138 of file Level1.java.
References clearElements(), Character.getHP(), Enemy.makeAngry(), Screen.showAndAnim(), and start().
Referenced by updateSprites().
void Level1.handleKeyInput (KeyEvent e) private
What to do each time a key is pressed
Definition at line 186 of file Level1.java.
Referenced by makeScene().
void Level1.handleKeyRelease (KeyEvent e) private
What to do when key is released
Definition at line 196 of file Level1.java.
Referenced by makeScene().
void Level1.handleMouseInput (MouseEvent e) private
What to do each time the mouse is clicked (create a shot)
Definition at line 218 of file Level1.java.
References Player.makeShot().
Referenced by makeScene().
Scene Level1.init (Stage s, int width, int height)
Create the game's scene
Definition at line 55 of file Level1.java.
References makeScene(), makeTimer(), and Sprite.setVelocity().
Scene Level1.makeScene (int width, int height) private
Create the game's scene
Definition at line 78 of file Level1.java.
References handleKeyInput(), handleKeyRelease(), handleMouseInput(), and myScene.
Referenced by init().
void Level1.makeTimer () private
Definition at line 111 of file Level1.java.
Referenced by init().
void Level1.removeFromScreen (ArrayList< Sprite > projectiles, ArrayList< Sprite > toRemoveArray) private
Definition at line 175 of file Level1.java.
Referenced by updateSprites().
ArrayList<Sprite> Level1.returnCollisions (Character character, ArrayList< Sprite > projectiles) private
Definition at line 165 of file Level1.java.
References Character.updateAll().
Referenced by updateSprites().
KeyFrame Level1.start (int frameRate)
Create the game's frame
Definition at line 89 of file Level1.java.
References updateFrame().
Referenced by Menu.createGame(), and goNextLevel().
void Level1.updateFrame () private
Definition at line 93 of file Level1.java.
References updateSprites(), and updateTimer().
Referenced by start().
void Level1.updateSprites () private
Definition at line 119 of file Level1.java.
References goGameOver(), goNextLevel(), Enemy.makePoop(), Player.moveSprite(), Enemy.moveSprite(), removeFromScreen(), and returnCollisions().
Referenced by updateFrame().
void Level1.updateTimer () private
2 methods that have to do with the timer
Definition at line 104 of file Level1.java.
Referenced by updateFrame().
Member Data Documentation
final int Level1.ENEMY_HP = 100 static private
Definition at line 34 of file Level1.java.
int Level1.frameCounter =0 private
Definition at line 46 of file Level1.java.
ArrayList<KeyCode> Level1.keysPressed private
Definition at line 42 of file Level1.java.
Enemy Level1.myEnemy private
Definition at line 40 of file Level1.java.
Referenced by getEnemy().
Random Level1.myGenerator = new Random() private
Definition at line 41 of file Level1.java.
Player Level1.myPlayer private
Definition at line 39 of file Level1.java.
Referenced by getPlayer().
Group Level1.myRoot private
Definition at line 38 of file Level1.java.
Scene Level1.myScene private
Definition at line 37 of file Level1.java.
Referenced by makeScene().
final int Level1.PLAYER_HP = 50 static private
Definition at line 33 of file Level1.java.
ArrayList<Sprite> Level1.Poops private
Definition at line 44 of file Level1.java.
double Level1.screenWidth private
Definition at line 36 of file Level1.java.
ArrayList<Sprite> Level1.Shots private
Definition at line 43 of file Level1.java.
Stage Level1.stage private
Definition at line 49 of file Level1.java.
final int Level1.START_TIME = 60 static private
Definition at line 35 of file Level1.java.
Label Level1.timerLabel private
Definition at line 45 of file Level1.java.
IntegerProperty Level1.timeSeconds private
Initial value:
=
            new SimpleIntegerProperty(START_TIME)
Definition at line 47 of file Level1.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Level1.java