game_mo82: Enemy Class Reference
Enemy Class Reference
Public Member Functions
Enemy (double X, double Y, double points, Group Root)
void makeAngry ()
Poop makePoop (Character player)
void moveSprite (double width)
Public Member Functions inherited from Character
Character (double X, double Y, double points, String fileName, Group myRoot)
boolean checkCollide (Sprite projectile)
void collisionUpdate (Sprite projectile, ArrayList< Sprite > shotsToRemove)
void updateAll (ArrayList< Sprite > shots, ArrayList< Sprite > shotsToRemove)
void setBarLocation (double X, double Y)
void setHP (double points)
void setFull ()
double getHP ()
Public Member Functions inherited from Sprite
Sprite (double X, double Y, String fileName, Group myRoot)
void moveSprite ()
void setVelocity (double X, double Y)
Point2D getVelocity ()
Private Attributes
Group myRoot
Random myGenerator = new Random()
boolean Angry =false
Additional Inherited Members
Protected Attributes inherited from Character
ProgressBar HPBar
Detailed Description
Definition at line 6 of file Enemy.java.
Constructor & Destructor Documentation
Enemy.Enemy (double X, double Y, double points, Group Root)
Definition at line 10 of file Enemy.java.
References Character.HPBar, Character.setBarLocation(), and Sprite.setVelocity().
Member Function Documentation
void Enemy.makeAngry ()
Definition at line 18 of file Enemy.java.
Referenced by Level1.goNextLevel().
Poop Enemy.makePoop (Character player)
Definition at line 22 of file Enemy.java.
References Sprite.setVelocity().
Referenced by Level1.updateSprites().
void Enemy.moveSprite (double width)
Definition at line 31 of file Enemy.java.
References Sprite.getVelocity(), Sprite.moveSprite(), and Sprite.setVelocity().
Referenced by Level1.updateSprites().
Member Data Documentation
boolean Enemy.Angry =false private
Definition at line 9 of file Enemy.java.
Random Enemy.myGenerator = new Random() private
Definition at line 8 of file Enemy.java.
Group Enemy.myRoot private
Definition at line 7 of file Enemy.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Enemy.java