game_mo82: Menu Class Reference
Menu Class Reference
Public Member Functions
Scene init (Stage s, int width, int height)
void addButton (double X, double Y, String text)
void addAllButtons ()
void handle (ActionEvent e)
void createGame (Level1 game)
Text addText (double X, double Y, double size, String text)
void addAllText ()
Public Member Functions inherited from Screen
void showScreen (Stage s, int width, int height)
Scene init (Stage s, int width, int height)
void startAnim (KeyFrame frame)
void showAndAnim (Stage s, int width, int height, KeyFrame frame)
Private Attributes
Group myRoot
Stage stage
Static Private Attributes
static final int NUM_FRAMES_PER_SECOND = 60
Additional Inherited Members
Protected Attributes inherited from Screen
Group myRoot
Detailed Description
Definition at line 15 of file Menu.java.
Member Function Documentation
void Menu.addAllButtons ()
Definition at line 39 of file Menu.java.
References addButton().
Referenced by init().
void Menu.addAllText ()
Definition at line 62 of file Menu.java.
References addText().
Referenced by init().
void Menu.addButton (double X, double Y, String text)
Definition at line 31 of file Menu.java.
References handle().
Referenced by GameOver.addAllButtons(), and addAllButtons().
Text Menu.addText (double X, double Y, double size, String text)
Definition at line 53 of file Menu.java.
Referenced by GameOver.addAllText(), and addAllText().
void Menu.createGame (Level1 game)
Definition at line 48 of file Menu.java.
References Screen.showAndAnim(), and Level1.start().
Referenced by handle().
void Menu.handle (ActionEvent e)
Definition at line 43 of file Menu.java.
References createGame().
Referenced by addButton().
Scene Menu.init (Stage s, int width, int height)
Definition at line 23 of file Menu.java.
References addAllButtons(), and addAllText().
Member Data Documentation
Group Menu.myRoot private
Definition at line 17 of file Menu.java.
final int Menu.NUM_FRAMES_PER_SECOND = 60 static private
Definition at line 21 of file Menu.java.
Stage Menu.stage private
Definition at line 18 of file Menu.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Menu.java