game_mo82: Character Class Reference
Character Class Reference
Public Member Functions
Character (double X, double Y, double points, String fileName, Group myRoot)
boolean checkCollide (Sprite projectile)
void collisionUpdate (Sprite projectile, ArrayList< Sprite > shotsToRemove)
void updateAll (ArrayList< Sprite > shots, ArrayList< Sprite > shotsToRemove)
void setBarLocation (double X, double Y)
void setHP (double points)
double getHP ()
Public Member Functions inherited from Sprite
Sprite (double X, double Y, String fileName, Group myRoot)
void moveSprite ()
void setVelocity (double X, double Y)
Point2D getVelocity ()
Protected Attributes
ProgressBar HPBar
Private Attributes
double fullHP
double HP
Static Private Attributes
static final int DAMAGE = 5
Detailed Description
Definition at line 9 of file Character.java.
Constructor & Destructor Documentation
Character.Character (double X, double Y, double points, String fileName, Group myRoot)
Definition at line 14 of file Character.java.
Member Function Documentation
boolean Character.checkCollide (Sprite projectile)
Definition at line 22 of file Character.java.
Referenced by collisionUpdate().
void Character.collisionUpdate (Sprite projectile, ArrayList< Sprite > shotsToRemove)
Definition at line 27 of file Character.java.
References checkCollide(), DAMAGE, and fullHP.
Referenced by updateAll().
double Character.getHP ()
Definition at line 50 of file Character.java.
References HP.
Referenced by Level1.goGameOver(), and Level1.goNextLevel().
void Character.setBarLocation (double X, double Y)
Definition at line 41 of file Character.java.
Referenced by Enemy.Enemy(), and Player.Player().
void Character.setHP (double points)
Definition at line 46 of file Character.java.
void Character.updateAll (ArrayList< Sprite > shots, ArrayList< Sprite > shotsToRemove)
Definition at line 35 of file Character.java.
References collisionUpdate().
Referenced by Level1.returnCollisions().
Member Data Documentation
final int Character.DAMAGE = 5 static private
Definition at line 10 of file Character.java.
Referenced by collisionUpdate().
double Character.fullHP private
Definition at line 11 of file Character.java.
Referenced by collisionUpdate().
double Character.HP private
Definition at line 12 of file Character.java.
Referenced by getHP().
ProgressBar Character.HPBar protected
Definition at line 13 of file Character.java.
Referenced by Enemy.Enemy(), and Player.Player().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/game_mo82/repository/CopiedExample/src/Character.java